# Generated by Django 5.2.7 on 2025-10-22 00:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rawg_id', models.IntegerField()),
                ('release_date', models.DateField()),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('post_date', models.DateTimeField()),
                ('edit_code', models.CharField(max_length=12)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_app.game')),
            ],
        ),
    ]
