# Generated by Django 5.2.7 on 2025-10-23 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='nickname',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Title', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='edit_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='review',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
